make fakechroot mode bit-by-bit identical to the others

diff --git a/mmdebstrap b/mmdebstrap
--- a/mmdebstrap
+++ b/mmdebstrap
@@ -251,6 +251,24 @@ sub get_tar_compressor {
     return;
 }
 
+# avoid dependency on String::ShellQuote by implementing the mechanism
+# from python's shlex.quote function
+sub shellescape {
+    my $string = shift;
+    if (length $string == 0) {
+        return "''";
+    }
+    # search for occurrences of characters that are not safe
+    # the 'a' regex modifier makes sure that \w only matches ASCII
+    if ($string !~ m/[^\w@\%+=:,.\/-]/a) {
+        return $string;
+    }
+    # wrap the string in single quotes and handle existing single quotes by
+    # putting them outside of the single-quoted string
+    $string =~ s/'/'"'"'/g;
+    return "'$string'";
+}
+
 sub test_unshare_userns {
     my $verbose = shift;
     if ($EFFECTIVE_USER_ID == 0) {
@@ -1977,16 +1995,15 @@ sub run_setup() {
         copy($tmpfile, \*STDERR);
     }
 
-    if (any { $_ eq $options->{mode} } ('fakechroot', 'proot')) {
+    if (none { $_ eq $options->{mode} } ('fakechroot', 'proot')) {
         # Apt dropping privileges to another user than root is not useful in
         # fakechroot and proot mode because all users are faked and thus there
-        # is no real privilege difference anyways. Thus, we also print no
-        # warning message in this case.
-        open my $fh, '>>', $tmpfile
-          or error "cannot open $tmpfile for appending: $!";
-        print $fh "APT::Sandbox::User \"root\";\n";
-        close $fh;
-    } else {
+        # is no real privilege difference anyways. We could set
+        # APT::Sandbox::User "root" in fakechroot and proot mode but we don't
+        # because if we would, then /var/cache/apt/archives/partial/ and
+        # /var/lib/apt/lists/partial/ would not be owned by the _apt user
+        # if mmdebstrap was run in fakechroot or proot mode.
+        #
         # when apt-get update is run by the root user, then apt will attempt to
         # drop privileges to the _apt user. This will fail if the _apt user
         # does not have permissions to read the root directory. In that case,
@@ -2643,11 +2660,28 @@ sub run_prepare {
         # /etc/fakechroot/debootstrap.env and
         # /etc/fakechroot/chroot.env
         {
+            # we add "$@" before "-r" such that any other "-r" options will be
+            # overwritten by the one we set
+            my $escapedroot = shellescape $options->{root};
+            my ($fh, $filename) = tempfile(
+                "mmdebstrap.ldconfig.XXXXXXXXXXXX",
+                UNLINK => 1,
+                TMPDIR => 1
+            );
+            print $fh <<EOF;
+#!/bin/sh
+set -e
+if [ ! -e $escapedroot/sbin/ldconfig ]; then exit 0; fi
+mkdir --mode=700 --parents $escapedroot/var/cache/ldconfig
+$escapedroot/sbin/ldconfig "\$@" -r $escapedroot
+EOF
+            close $fh;
+            chmod 0755, $filename or error "cannot chmod $filename";
             my @fakechrootsubst = ();
             foreach my $d ('/usr/sbin', '/usr/bin', '/sbin', '/bin') {
                 push @fakechrootsubst, "$d/chroot=/usr/sbin/chroot.fakechroot";
                 push @fakechrootsubst, "$d/mkfifo=/bin/true";
-                push @fakechrootsubst, "$d/ldconfig=/bin/true";
+                push @fakechrootsubst, "$d/ldconfig=$filename";
                 push @fakechrootsubst, "$d/ldd=/usr/bin/ldd.fakechroot";
                 push @fakechrootsubst, "$d/ischroot=/bin/true";
             }
@@ -5684,6 +5718,12 @@ sub main() {
                 }
 
                 if ($options->{mode} eq 'fakechroot') {
+                    # By default, FAKECHROOT_EXCLUDE_PATH includes /proc and
+                    # /sys which means that the resulting tarball will contain
+                    # the permission and ownership information of /proc and
+                    # /sys from the outside, which we want to avoid.
+                    ## no critic (Variables::RequireLocalizedPunctuationVars)
+                    $ENV{FAKECHROOT_EXCLUDE_PATH} = "/dev";
                     # Fakechroot requires tar to run inside the chroot or
                     # otherwise absolute symlinks will include the path to the
                     # root directory
