format shell scripts with shfmt --binary-next-line --case-indent --indent 2 --simplify

diff --git a/mmdebstrap-autopkgtest-build-qemu b/mmdebstrap-autopkgtest-build-qemu
--- a/mmdebstrap-autopkgtest-build-qemu
+++ b/mmdebstrap-autopkgtest-build-qemu
@@ -127,15 +127,15 @@ POD2MAN
 set -eu
 
 die() {
-	echo "$*" 1>&2
-	exit 1
+  echo "$*" 1>&2
+  exit 1
 }
 usage() {
-	die "usage: $0 [--architecture=|--apt-proxy=|--keyring=|--mirror=|--script=|--size=] --boot=efi <RELEASE> <IMAGE>"
+  die "usage: $0 [--architecture=|--apt-proxy=|--keyring=|--mirror=|--script=|--size=] --boot=efi <RELEASE> <IMAGE>"
 }
 usage_error() {
-	echo "error: $*" 1>&2
-	usage
+  echo "error: $*" 1>&2
+  usage
 }
 
 BOOT=auto
@@ -151,164 +151,164 @@ SCRIPT=
 export AUTOPKGTEST_BUILD_QEMU=1
 
 opt_boot() {
-	BOOT="$1"
+  BOOT="$1"
 }
 opt_architecture() {
-	ARCHITECTURE="$1"
+  ARCHITECTURE="$1"
 }
 opt_arch() {
-	ARCHITECTURE="$1"
+  ARCHITECTURE="$1"
 }
 opt_apt_proxy() {
-	# consumed by setup-testbed
-	export AUTOPKGTEST_APT_PROXY="$1"
-	# consumed by mmdebstrap
-	if test "$1" = DIRECT; then
-		unset http_proxy
-	else
-		export http_proxy="$1"
-	fi
+  # consumed by setup-testbed
+  export AUTOPKGTEST_APT_PROXY="$1"
+  # consumed by mmdebstrap
+  if test "$1" = DIRECT; then
+    unset http_proxy
+  else
+    export http_proxy="$1"
+  fi
 }
 opt_keyring() {
-	KEYRING="$1"
+  KEYRING="$1"
 }
 opt_mirror() {
-	# consumed by setup-testbed
-	export MIRROR="$1"
+  # consumed by setup-testbed
+  export MIRROR="$1"
 }
 opt_script() {
-	test -f "$1" || die "passed script '$1' does not refer to a file"
-	SCRIPT="$1"
+  test -f "$1" || die "passed script '$1' does not refer to a file"
+  SCRIPT="$1"
 }
 opt_size() {
-	SIZE="$1"
+  SIZE="$1"
 }
 
 positional=1
 positional_1() {
-	# consumed by setup-testbed
-	export RELEASE="$1"
+  # consumed by setup-testbed
+  export RELEASE="$1"
 }
 positional_2() {
-	IMAGE="$1"
+  IMAGE="$1"
 }
 positional_3() { opt_mirror "$@"; }
 positional_4() { opt_architecture "$@"; }
 positional_5() { opt_script "$@"; }
 positional_6() { opt_size "$@"; }
 positional_7() {
-	die "too many positional options"
+  die "too many positional options"
 }
 
 while test "$#" -gt 0; do
-	case "$1" in
-		--architecture=*|--arch=*|--boot=*|--keyring=*|--mirror=*|--script=*|--size=*)
-			optname="${1%%=*}"
-			"opt_${optname#--}" "${1#*=}"
-		;;
-		--apt-proxy=*)
-			opt_apt_proxy "${1#*=}"
-		;;
-		--architecture|--arch|--boot|--keyring|--mirror|--script|--size)
-			test "$#" -ge 2 || usage_error "missing argument for $1"
-			"opt_${1#--}" "$2"
-			shift
-		;;
-		--apt-proxy)
-			test "$#" -ge 2 || usage_error "missing argument for $1"
-			opt_apt_proxy "$2"
-			shift
-		;;
-		--efi)
-			opt_boot efi
-		;;
-		--*)
-			usage_error "unrecognized argument $1"
-		;;
-		*)
-			"positional_$positional" "$1"
-			positional=$((positional + 1))
-		;;
-	esac
-	shift
+  case "$1" in
+    --architecture=* | --arch=* | --boot=* | --keyring=* | --mirror=* | --script=* | --size=*)
+      optname="${1%%=*}"
+      "opt_${optname#--}" "${1#*=}"
+      ;;
+    --apt-proxy=*)
+      opt_apt_proxy "${1#*=}"
+      ;;
+    --architecture | --arch | --boot | --keyring | --mirror | --script | --size)
+      test "$#" -ge 2 || usage_error "missing argument for $1"
+      "opt_${1#--}" "$2"
+      shift
+      ;;
+    --apt-proxy)
+      test "$#" -ge 2 || usage_error "missing argument for $1"
+      opt_apt_proxy "$2"
+      shift
+      ;;
+    --efi)
+      opt_boot efi
+      ;;
+    --*)
+      usage_error "unrecognized argument $1"
+      ;;
+    *)
+      "positional_$positional" "$1"
+      positional=$((positional + 1))
+      ;;
+  esac
+  shift
 done
 
 test -z "$RELEASE" -o -z "$IMAGE" && usage_error "missing positional arguments"
-test "$BOOT" = efi ||
-	die "this tool does not support boot modes other than efi"
+test "$BOOT" = efi \
+  || die "this tool does not support boot modes other than efi"
 
 case "$ARCHITECTURE" in
-	amd64)
-		EFIIMG=bootx64.efi
-		QEMUARCH=x86_64
-		VMFPKG=ovmf
-		LINUXIMAGE=linux-image-amd64
-	;;
-	arm64)
-		EFIIMG=bootaa64.efi
-		QEMUARCH=aarch64
-		VMFPKG=qemu-efi-aarch64
-		LINUXIMAGE=linux-image-arm64
-	;;
-	armhf)
-		EFIIMG=bootarm.efi
-		QEMUARCH=arm
-		VMFPKG=qemu-efi-arm
-		LINUXIMAGE=linux-image-armmp
-	;;
-	i386)
-		EFIIMG=bootia32.efi
-		QEMUARCH=i386
-		VMFPKG=ovmf-ia32
-		LINUXIMAGE=linux-image-686-pae
-	;;
-	riscv64)
-		EFIIMG=bootriscv64.efi
-		QEMUARCH=riscv64
-		VMFPKG=
-		LINUXIMAGE=linux-image-riscv64
-	;;
-	*)
-		die "unsupported architecture: $ARCHITECTURE"
-	;;
+  amd64)
+    EFIIMG=bootx64.efi
+    QEMUARCH=x86_64
+    VMFPKG=ovmf
+    LINUXIMAGE=linux-image-amd64
+    ;;
+  arm64)
+    EFIIMG=bootaa64.efi
+    QEMUARCH=aarch64
+    VMFPKG=qemu-efi-aarch64
+    LINUXIMAGE=linux-image-arm64
+    ;;
+  armhf)
+    EFIIMG=bootarm.efi
+    QEMUARCH=arm
+    VMFPKG=qemu-efi-arm
+    LINUXIMAGE=linux-image-armmp
+    ;;
+  i386)
+    EFIIMG=bootia32.efi
+    QEMUARCH=i386
+    VMFPKG=ovmf-ia32
+    LINUXIMAGE=linux-image-686-pae
+    ;;
+  riscv64)
+    EFIIMG=bootriscv64.efi
+    QEMUARCH=riscv64
+    VMFPKG=
+    LINUXIMAGE=linux-image-riscv64
+    ;;
+  *)
+    die "unsupported architecture: $ARCHITECTURE"
+    ;;
 esac
 
 if test "$(dpkg-query -f '${db:Status-Status}' -W binutils-multiarch)" = installed; then
-	GNU_PREFIX=
-	BINUTILS=
+  GNU_PREFIX=
+  BINUTILS=
 else
-	GNU_ARCHITECTURE="$(dpkg-architecture "-a$ARCHITECTURE" -qDEB_HOST_GNU_TYPE)"
-	GNU_PREFIX="$GNU_ARCHITECTURE-"
-	GNU_SUFFIX="-$(echo "$GNU_ARCHITECTURE" | tr _ -)"
-	BINUTILS=", binutils$GNU_SUFFIX | binutils-multiarch"
+  GNU_ARCHITECTURE="$(dpkg-architecture "-a$ARCHITECTURE" -qDEB_HOST_GNU_TYPE)"
+  GNU_PREFIX="$GNU_ARCHITECTURE-"
+  GNU_SUFFIX="-$(echo "$GNU_ARCHITECTURE" | tr _ -)"
+  BINUTILS=", binutils$GNU_SUFFIX | binutils-multiarch"
 fi
 
 arches=" $(dpkg --print-architecture) $(dpkg --print-foreign-architectures | tr '\n' ' ') "
 case $arches in
-	*" $ARCHITECTURE "*) : ;; # nothing to do
-	*) die "enable $ARCHITECTURE by running: sudo dpkg --add-architecture $ARCHITECTURE && sudo apt update" ;;
+  *" $ARCHITECTURE "*) : ;; # nothing to do
+  *) die "enable $ARCHITECTURE by running: sudo dpkg --add-architecture $ARCHITECTURE && sudo apt update" ;;
 esac
 
-test "$(dpkg-query -f '${db:Status-Status}' -W "dpkg-dev")" = installed ||
-	die "please install dpkg-dev"
+test "$(dpkg-query -f '${db:Status-Status}' -W "dpkg-dev")" = installed \
+  || die "please install dpkg-dev"
 
-dpkg-checkbuilddeps -d "autopkgtest, dosfstools, e2fsprogs, fdisk, mount, mtools, passwd, uidmap, libarchive13, systemd-boot-efi:$ARCHITECTURE $BINUTILS" /dev/null ||
-	die "please install the required packages listed above"
+dpkg-checkbuilddeps -d "autopkgtest, dosfstools, e2fsprogs, fdisk, mount, mtools, passwd, uidmap, libarchive13, systemd-boot-efi:$ARCHITECTURE $BINUTILS" /dev/null \
+  || die "please install the required packages listed above"
 
 BOOTSTUB="/usr/lib/systemd/boot/efi/linux${EFIIMG#boot}.stub"
 
 WORKDIR=
 
 cleanup() {
-	test -n "$WORKDIR" && rm -Rf "$WORKDIR"
+  test -n "$WORKDIR" && rm -Rf "$WORKDIR"
 }
 
 trap cleanup EXIT INT TERM QUIT
 
 WORKDIR=$(mktemp -d)
 
-FAT_OFFSET_SECTORS=$((1024*2))
-FAT_SIZE_SECTORS=$((1024*254))
+FAT_OFFSET_SECTORS=$((1024 * 2))
+FAT_SIZE_SECTORS=$((1024 * 254))
 
 # The image is raw and not in qcow2 format because:
 #  - faster run-time as the "qemu-image convert" step is not needed
@@ -321,44 +321,45 @@ FAT_SIZE_SECTORS=$((1024*254))
 #    custom options like compression
 
 set -- \
-	--mode=unshare \
-	--format=tar \
-	--variant=important \
-	--architecture="$ARCHITECTURE"
+  --mode=unshare \
+  --format=tar \
+  --variant=important \
+  --architecture="$ARCHITECTURE"
 
-case $MIRROR in http://snapshot.debian.org/archive/*|https://snapshot.debian.org/archive/*)
-	set -- "$@" --aptopt='Acquire::Check-Valid-Until "false"';;
+case $MIRROR in http://snapshot.debian.org/archive/* | https://snapshot.debian.org/archive/*)
+  set -- "$@" --aptopt='Acquire::Check-Valid-Until "false"'
+  ;;
 esac
 
 EXT_FEATURES=
 if test "$RELEASE" = jessie; then
-	set -- "$@" --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg
-	set -- "$@" --aptopt='Apt::Key::gpgvcommand "/usr/libexec/mmdebstrap/gpgvnoexpkeysig"'
-	set -- "$@" --hook-dir=/usr/share/mmdebstrap/hooks/jessie-or-older
-	EXT_FEATURES="^metadata_csum,^metadata_csum_seed,^orphan_file"
+  set -- "$@" --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg
+  set -- "$@" --aptopt='Apt::Key::gpgvcommand "/usr/libexec/mmdebstrap/gpgvnoexpkeysig"'
+  set -- "$@" --hook-dir=/usr/share/mmdebstrap/hooks/jessie-or-older
+  EXT_FEATURES="^metadata_csum,^metadata_csum_seed,^orphan_file"
 fi
 
 set -- "$@" \
-	"--include=init,$LINUXIMAGE,python3" \
-	'--customize-hook=echo host >"$1/etc/hostname"' \
-	'--customize-hook=echo 127.0.0.1 localhost host >"$1/etc/hosts"' \
-	'--customize-hook=passwd --root "$1" --delete root' \
-	'--customize-hook=useradd --root "$1" --home-dir /home/user --create-home user' \
-	'--customize-hook=passwd --root "$1" --delete user' \
-	'--customize-hook=/usr/share/autopkgtest/setup-commands/setup-testbed'
+  "--include=init,$LINUXIMAGE,python3" \
+  '--customize-hook=echo host >"$1/etc/hostname"' \
+  '--customize-hook=echo 127.0.0.1 localhost host >"$1/etc/hosts"' \
+  '--customize-hook=passwd --root "$1" --delete root' \
+  '--customize-hook=useradd --root "$1" --home-dir /home/user --create-home user' \
+  '--customize-hook=passwd --root "$1" --delete user' \
+  '--customize-hook=/usr/share/autopkgtest/setup-commands/setup-testbed'
 
 if test -n "$SCRIPT"; then
-	set -- "$@" \
-		"--customize-hook=upload '$SCRIPT' /userscript" \
-		"--chrooted-customize-hook=sh /userscript" \
-		'--customize-hook=rm -f "$1/userscript"'
+  set -- "$@" \
+    "--customize-hook=upload '$SCRIPT' /userscript" \
+    "--chrooted-customize-hook=sh /userscript" \
+    '--customize-hook=rm -f "$1/userscript"'
 fi
 
 set -- "$@" \
-	"--customize-hook=download vmlinuz '$WORKDIR/kernel'" \
-	"--customize-hook=download initrd.img '$WORKDIR/initrd'" \
-	"$RELEASE" \
-	-
+  "--customize-hook=download vmlinuz '$WORKDIR/kernel'" \
+  "--customize-hook=download initrd.img '$WORKDIR/initrd'" \
+  "$RELEASE" \
+  -
 
 test -n "$MIRROR" && set -- "$@" "$MIRROR"
 test -n "$KEYRING" && set -- "$@" "--keyring=$KEYRING"
@@ -368,45 +369,44 @@ echo "+ mmdebstrap $*" >&2
 # shellcheck disable=SC3040
 set -o pipefail
 mmdebstrap "$@" | {
-	set -- -t ext4 -L autopkgtestvm -d -
-	if test -n "$EXT_FEATURES"; then
-		set -- "$@" -O "$EXT_FEATURES"
-	fi
-	EXTOPTS="offset=$(( (FAT_OFFSET_SECTORS + FAT_SIZE_SECTORS) * 512))"
-	if test -n "${SOURCE_DATE_EPOCH:-}"; then
-		uuid="$(uuidgen --sha1 --namespace="$(uuidgen --sha1 --namespace='@dns' --name mister-muffin.de)" --name "$SOURCE_DATE_EPOCH")"
-		set -- "$@" -U "$uuid"
-		EXTOPTS="$EXTOPTS,hash_seed=$uuid"
-	fi
-	set -- "$@" -E "$EXTOPTS" "$IMAGE" "$SIZE"
-	echo "+ mke2fs $*" >&2
-	/sbin/mke2fs "$@"
+  set -- -t ext4 -L autopkgtestvm -d -
+  if test -n "$EXT_FEATURES"; then
+    set -- "$@" -O "$EXT_FEATURES"
+  fi
+  EXTOPTS="offset=$(((FAT_OFFSET_SECTORS + FAT_SIZE_SECTORS) * 512))"
+  if test -n "${SOURCE_DATE_EPOCH-}"; then
+    uuid="$(uuidgen --sha1 --namespace="$(uuidgen --sha1 --namespace='@dns' --name mister-muffin.de)" --name "$SOURCE_DATE_EPOCH")"
+    set -- "$@" -U "$uuid"
+    EXTOPTS="$EXTOPTS,hash_seed=$uuid"
+  fi
+  set -- "$@" -E "$EXTOPTS" "$IMAGE" "$SIZE"
+  echo "+ mke2fs $*" >&2
+  /sbin/mke2fs "$@"
 }
 
-
-echo "root=LABEL=autopkgtestvm rw console=ttyS0" > "$WORKDIR/cmdline"
+echo "root=LABEL=autopkgtestvm rw console=ttyS0" >"$WORKDIR/cmdline"
 
 align_size() {
-	echo "$(( ($1) + ($2) - 1 - (($1) + ($2) - 1) % ($2) ))"
+  echo "$((($1) + ($2) - 1 - (($1) + ($2) - 1) % ($2)))"
 }
 
 alignment=$("${GNU_PREFIX}objdump" -p "$BOOTSTUB" | sed 's/^SectionAlignment\s\+\([0-9]\)/0x/;t;d')
 test -z "$alignment" && die "failed to discover the alignment of the efi stub"
 echo "determined efi vma alignment as $alignment"
-test "$RELEASE" = jessie -a "$((alignment))" -lt "$((1024*1024))" && {
-	echo "increasing efi vma alignment for jessie"
-	alignment=$((1024*1024))
+test "$RELEASE" = jessie -a "$((alignment))" -lt "$((1024 * 1024))" && {
+  echo "increasing efi vma alignment for jessie"
+  alignment=$((1024 * 1024))
 }
 lastoffset=0
 # shellcheck disable=SC2034  # unused variables serve documentation
-lastoffset="$("${GNU_PREFIX}objdump" -h "$BOOTSTUB" |
-	while read -r idx name size vma lma fileoff algn behind; do
-		test -z "$behind" -a "${algn#"2**"}" != "$algn" || continue
-		offset=$(( 0x$vma + 0x$size ))
-		test "$offset" -gt "$lastoffset" || continue
-		lastoffset="$offset"
-		echo "$lastoffset"
-	done | tail -n1)"
+lastoffset="$("${GNU_PREFIX}objdump" -h "$BOOTSTUB" \
+  | while read -r idx name size vma lma fileoff algn behind; do
+    test -z "$behind" -a "${algn#"2**"}" != "$algn" || continue
+    offset=$((0x$vma + 0x$size))
+    test "$offset" -gt "$lastoffset" || continue
+    lastoffset="$offset"
+    echo "$lastoffset"
+  done | tail -n1)"
 lastoffset=$(align_size "$lastoffset" "$alignment")
 echo "determined minimum efi vma offset as $lastoffset"
 
@@ -419,15 +419,15 @@ linux_offset=$((cmdline_offset + cmdline_size))
 initrd_offset=$((linux_offset + linux_size))
 
 SOURCE_DATE_EPOCH=0 \
-	"${GNU_PREFIX}objcopy" \
-	--enable-deterministic-archives \
-	--add-section .cmdline="$WORKDIR/cmdline" \
-	--change-section-vma .cmdline="$(printf 0x%x "$cmdline_offset")" \
-	--add-section .linux="$WORKDIR/kernel" \
-	--change-section-vma .linux="$(printf 0x%x "$linux_offset")" \
-	--add-section .initrd="$WORKDIR/initrd" \
-	--change-section-vma .initrd="$(printf 0x%x "$initrd_offset")" \
-	"$BOOTSTUB" "$WORKDIR/efiimg"
+  "${GNU_PREFIX}objcopy" \
+  --enable-deterministic-archives \
+  --add-section .cmdline="$WORKDIR/cmdline" \
+  --change-section-vma .cmdline="$(printf 0x%x "$cmdline_offset")" \
+  --add-section .linux="$WORKDIR/kernel" \
+  --change-section-vma .linux="$(printf 0x%x "$linux_offset")" \
+  --add-section .initrd="$WORKDIR/initrd" \
+  --change-section-vma .initrd="$(printf 0x%x "$initrd_offset")" \
+  "$BOOTSTUB" "$WORKDIR/efiimg"
 
 rm -f "$WORKDIR/kernel" "$WORKDIR/initrd"
 
@@ -438,7 +438,7 @@ mcopy -i "$WORKDIR/fat" "$WORKDIR/efiimg" "::EFI/BOOT/$EFIIMG"
 
 rm -f "$WORKDIR/efiimg"
 
-truncate --size="+$((34*512))" "$IMAGE"
+truncate --size="+$((34 * 512))" "$IMAGE"
 /sbin/sfdisk "$IMAGE" <<EOF
 label: gpt
 unit: sectors
@@ -450,10 +450,10 @@ EOF
 dd if="$WORKDIR/fat" of="$IMAGE" conv=notrunc,sparse bs=512 "seek=$FAT_OFFSET_SECTORS" status=none
 
 if test "$(dpkg --print-architecture)" != "$ARCHITECTURE" && test "$(dpkg-query -f '${db:Status-Status}' -W "qemu-system-$QEMUARCH")" != installed; then
-	echo "I: you might need to install a package providing qemu-system-$QEMUARCH to use this image with autopkgtest-virt-qemu" >&2
+  echo "I: you might need to install a package providing qemu-system-$QEMUARCH to use this image with autopkgtest-virt-qemu" >&2
 fi
 if test -n "$VMFPKG" && test "$(dpkg-query -f '${db:Status-Status}' -W "$VMFPKG")" != installed; then
-	echo "I: you might need to install $VMFPKG to use this image with autopkgtest-virt-qemu" >&2
+  echo "I: you might need to install $VMFPKG to use this image with autopkgtest-virt-qemu" >&2
 fi
 
 echo "I: SUCCESS! Your new image can be found here: $IMAGE" >&2
diff --git a/tests/debootstrap b/tests/debootstrap
--- a/tests/debootstrap
+++ b/tests/debootstrap
@@ -8,9 +8,9 @@ chmod 755 "$tmpdir"
 ret=0
 debootstrap "$([ "{{ DIST }}" = oldstable ] && echo --no-merged-usr || echo --merged-usr)" --variant={{ VARIANT }} {{ DIST }} "$tmpdir" {{ MIRROR }} || ret=$?
 if [ "$ret" -ne 0 ]; then
-	echo "E: debootstrap failed, dumping $tmpdir/debootstrap/debootstrap.log"
-	cat "$tmpdir/debootstrap/debootstrap.log"
-	exit 1
+  echo "E: debootstrap failed, dumping $tmpdir/debootstrap/debootstrap.log"
+  cat "$tmpdir/debootstrap/debootstrap.log"
+  exit 1
 fi
-tar --sort=name --mtime=@$SOURCE_DATE_EPOCH --clamp-mtime --numeric-owner --one-file-system --xattrs -C "$tmpdir" -c . > "./cache/debian-{{ DIST }}-{{ VARIANT }}.tar"
+tar --sort=name --mtime=@$SOURCE_DATE_EPOCH --clamp-mtime --numeric-owner --one-file-system --xattrs -C "$tmpdir" -c . >"./cache/debian-{{ DIST }}-{{ VARIANT }}.tar"
 rm -r "$tmpdir"
diff --git a/tests/dev-ptmx b/tests/dev-ptmx
--- a/tests/dev-ptmx
+++ b/tests/dev-ptmx
@@ -3,24 +3,24 @@ set -eu
 export LC_ALL=C.UTF-8
 
 if [ {{ MODE }} != unshare ] && [ {{ MODE }} != root ]; then
-	echo "test requires root or unshare mode" >&2
-	exit 1
+  echo "test requires root or unshare mode" >&2
+  exit 1
 fi
 
 prefix=
 if [ "$(id -u)" -eq 0 ] && [ "{{ MODE }}" != "root" ] && [ "{{ MODE }}" != "auto" ]; then
-	if ! id "${SUDO_USER:-user}" >/dev/null 2>&1; then
-		if [ ! -e /mmdebstrap-testenv ]; then
-			echo "this test modifies the system and should only be run inside a container" >&2
-			exit 1
-		fi
-		useradd --home-dir "/home/${SUDO_USER:-user}" --create-home "${SUDO_USER:-user}"
-	fi
-	prefix="runuser -u ${SUDO_USER:-user} --"
+  if ! id "${SUDO_USER:-user}" >/dev/null 2>&1; then
+    if [ ! -e /mmdebstrap-testenv ]; then
+      echo "this test modifies the system and should only be run inside a container" >&2
+      exit 1
+    fi
+    useradd --home-dir "/home/${SUDO_USER:-user}" --create-home "${SUDO_USER:-user}"
+  fi
+  prefix="runuser -u ${SUDO_USER:-user} --"
 fi
 
 # this mimics what apt does in apt-pkg/deb/dpkgpm.cc/pkgDPkgPM::StartPtyMagic()
-cat > /tmp/test.c << 'END'
+cat >/tmp/test.c <<'END'
 #define _GNU_SOURCE
 
 #include <stdlib.h>
@@ -141,9 +141,9 @@ grep 'Can not write log' /tmp/log && fail=1
 grep 'posix_openpt' /tmp/log && fail=1
 grep 'No such file or directory' /tmp/log && fail=1
 if [ $fail -eq 1 ]; then
-	echo "apt failed to write log:" >&2
-	cat /tmp/log >&2
-	exit 1
+  echo "apt failed to write log:" >&2
+  cat /tmp/log >&2
+  exit 1
 fi
 
 rm /tmp/test.c /tmp/log
diff --git a/tests/unshare-include-deb b/tests/unshare-include-deb
--- a/tests/unshare-include-deb
+++ b/tests/unshare-include-deb
@@ -9,21 +9,21 @@ trap "rm -rf /tmp/dummypkg.deb /tmp/dummypkg" EXIT INT TERM
 
 prefix=
 if [ "$(id -u)" -eq 0 ] && [ "{{ MODE }}" != "root" ] && [ "{{ MODE }}" != "auto" ]; then
-	if ! id "${SUDO_USER:-user}" >/dev/null 2>&1; then
-		if [ ! -e /mmdebstrap-testenv ]; then
-			echo "this test modifies the system and should only be run inside a container" >&2
-			exit 1
-		fi
-		useradd --home-dir "/home/${SUDO_USER:-user}" --create-home "${SUDO_USER:-user}"
-	fi
-	prefix="runuser -u ${SUDO_USER:-user} --"
+  if ! id "${SUDO_USER:-user}" >/dev/null 2>&1; then
+    if [ ! -e /mmdebstrap-testenv ]; then
+      echo "this test modifies the system and should only be run inside a container" >&2
+      exit 1
+    fi
+    useradd --home-dir "/home/${SUDO_USER:-user}" --create-home "${SUDO_USER:-user}"
+  fi
+  prefix="runuser -u ${SUDO_USER:-user} --"
 fi
 
 # instead of obtaining a .deb from our cache, we create a new package because
 # otherwise apt might decide to download the package with the same name and
 # version from the cache instead of using the local .deb
 mkdir -p /tmp/dummypkg/DEBIAN
-cat << END > "/tmp/dummypkg/DEBIAN/control"
+cat <<END >"/tmp/dummypkg/DEBIAN/control"
 Package: dummypkg
 Priority: optional
 Section: oldlibs
@@ -41,9 +41,9 @@ chmod 600 /tmp/dummypkg.deb
 
 ret=0
 $prefix {{ CMD }} --variant=apt --mode={{ MODE }} --include="/tmp/dummypkg.deb" \
-	{{ DIST }} /dev/null {{ MIRROR }} || ret=$?
+  {{ DIST }} /dev/null {{ MIRROR }} || ret=$?
 
 if [ "$ret" -eq 0 ]; then
-	echo "expected failure but got exit $ret" >&2
-	exit 1
+  echo "expected failure but got exit $ret" >&2
+  exit 1
 fi
